import { z } from "zod";
import {
  ASSET_STATUSES,
  ASSET_OWNERSHIP_TYPES,
  ASSET_CRITICALITY_LEVELS,
  ASSET_ASSIGNMENT_STATUSES,
  ASSET_DEPRECIATION_METHODS,
} from "../../models/Asset";
import { ASSET_DOCUMENT_TYPES } from "../../models/AssetDocument";

const objectId = z.string().min(1);
const str = () => z.string().optional().default("");
const importStr = () => z.string().max(500).optional().default("");

export const createAssetSchema = z.object({
  // Only ever honored when the caller has assets:editAssetId (enforced in the controller, which
  // strips this field before it reaches the service otherwise) - omitted, it falls back to the
  // existing auto-generated VNR-<category>-000001 sequence.
  assetId: z.string().trim().min(1).optional(),
  assetTag: z.string().trim().max(100).optional().default(""),
  name: z.string().min(1),
  category: objectId,
  assetType: str(),
  assetSubType: str(),
  ownershipType: z.enum(ASSET_OWNERSHIP_TYPES).optional(),
  criticality: z.enum(ASSET_CRITICALITY_LEVELS).optional(),
  companyEntity: str(),
  description: z.string().max(2000).optional().default(""),
  deviceType: str(),
  manufacturer: str(),
  model: str(),
  serialNumber: str(),
  serviceTag: str(),
  imei: str(),
  color: str(),
  hostname: str(),
  ipAddress: str(),
  macAddress: str(),
  operatingSystem: str(),
  operatingSystemLicense: str(),
  configuration: str(),
  processor: str(),
  laptopGeneration: str(),
  graphicsCard: str(),
  ram: str(),
  storage: str(),
  adapterSerialNumber: str(),
  miscAccessories: str(),
  adMember: str(),
  antivirusInstalled: str(),
  remoteSoftware: str(),
  emailLicense: str(),
  canvaLicense: str(),
  microsoftOffice: str(),
  microsoftProject: str(),
  powerBi: str(),
  autoCad: str(),
  zwCad: str(),
  photoshop: str(),
  creativeCloudPro: str(),
  illustrator: str(),
  acrobatPro: str(),
  sketchUpPro: str(),
  rocketReachPro: str(),
  d5Render: str(),
  zoomLicense: str(),
  sharedFolderAccess: str(),
  purchaseDate: z.coerce.date().optional(),
  purchaseCost: z.coerce.number().nonnegative().optional(),
  quantity: z.coerce.number().nonnegative().optional(),
  vendor: objectId.optional(),
  purchaseOrderNumber: str(),
  invoiceNumber: str(),
  currency: str(),
  contractNumber: str(),
  costCenter: str(),
  budgetCode: str(),
  depreciationMethod: z.enum(ASSET_DEPRECIATION_METHODS).optional(),
  depreciationStartDate: z.coerce.date().optional(),
  warrantyStartDate: z.coerce.date().optional(),
  warrantyEndDate: z.coerce.date().optional(),
  warrantyProvider: str(),
  supportContract: str(),
  contractStartDate: z.coerce.date().optional(),
  contractEndDate: z.coerce.date().optional(),
  location: objectId.optional(),
  building: str(),
  floor: str(),
  room: str(),
  subLocation: str(),
  department: objectId.optional(),
  assignedUser: objectId.nullable().optional(),
  assignmentDate: z.coerce.date().optional(),
  returnDate: z.coerce.date().optional(),
  assignmentStatus: z.enum(ASSET_ASSIGNMENT_STATUSES).optional(),
  status: z.enum(ASSET_STATUSES).optional(),
  condition: str(),
  repairHistory: str(),
  // Real per-field validation (required-ness, type, select options) happens server-side in
  // validateCustomFieldValues, not here - this just needs to not strip or reject the field.
  customFields: z.record(z.string(), z.unknown()).optional(),
});

export const updateAssetSchema = createAssetSchema.partial();

export const listAssetsQuerySchema = z.object({
  page: z.coerce.number().int().positive().optional(),
  limit: z.coerce.number().int().positive().max(100).optional(),
  search: z.string().max(100).optional(),
  status: z.enum(ASSET_STATUSES).optional(),
  ownershipType: z.enum(ASSET_OWNERSHIP_TYPES).optional(),
  criticality: z.enum(ASSET_CRITICALITY_LEVELS).optional(),
  assignmentStatus: z.enum(ASSET_ASSIGNMENT_STATUSES).optional(),
  category: objectId.optional(),
  location: objectId.optional(),
  department: objectId.optional(),
  vendor: objectId.optional(),
  purchaseDateFrom: z.coerce.date().optional(),
  purchaseDateTo: z.coerce.date().optional(),
  sortBy: z.enum(["name", "assetId", "purchaseDate", "createdDate", "status"]).optional(),
  sortDir: z.enum(["asc", "desc"]).optional(),
});

export const assetIdParamsSchema = z.object({
  id: z.string().min(1),
});

export const bulkDeleteAssetsSchema = z.object({
  ids: z.array(objectId).min(1, "Select at least one asset"),
});

export const assetDocumentParamsSchema = z.object({
  id: z.string().min(1),
  docId: z.string().min(1),
});

export const uploadAssetDocumentBodySchema = z.object({
  type: z.enum(ASSET_DOCUMENT_TYPES).optional().default("Other"),
});

const mappedAssetImportRowSchema = z.object({
  assetIdRaw: importStr(),
  assetTag: importStr(),
  name: importStr(),
  assetType: importStr(),
  assetSubType: importStr(),
  ownershipType: importStr(),
  criticality: importStr(),
  companyEntity: importStr(),
  description: importStr(),
  deviceType: importStr(),
  manufacturer: importStr(),
  model: importStr(),
  serialNumber: importStr(),
  imei: importStr(),
  color: importStr(),
  processor: importStr(),
  laptopGeneration: importStr(),
  graphicsCard: importStr(),
  ram: importStr(),
  storage: importStr(),
  macAddress: importStr(),
  adapterSerialNumber: importStr(),
  miscAccessories: importStr(),
  operatingSystem: importStr(),
  operatingSystemLicense: importStr(),
  canvaLicense: importStr(),
  hostname: importStr(),
  adMember: importStr(),
  antivirusInstalled: importStr(),
  remoteSoftware: importStr(),
  emailLicense: importStr(),
  microsoftOffice: importStr(),
  microsoftProject: importStr(),
  powerBi: importStr(),
  autoCad: importStr(),
  zwCad: importStr(),
  photoshop: importStr(),
  creativeCloudPro: importStr(),
  illustrator: importStr(),
  acrobatPro: importStr(),
  sketchUpPro: importStr(),
  rocketReachPro: importStr(),
  d5Render: importStr(),
  zoomLicense: importStr(),
  sharedFolderAccess: importStr(),
  status: importStr(),
  condition: importStr(),
  conditionNotes: importStr(),
  approvalStatus: importStr(),
  repairHistory: importStr(),
  purchaseDate: importStr(),
  purchaseCost: importStr(),
  quantity: importStr(),
  warrantyEnd: importStr(),
  invoiceNumber: importStr(),
  companyName: importStr(),
  notes: importStr(),
  categoryName: importStr(),
  locationName: importStr(),
  subLocation: importStr(),
  departmentName: importStr(),
  vendorName: importStr(),
  employeeName: importStr(),
  employeeId: importStr(),
  designation: importStr(),
  email: importStr(),
  userAccessLevel: importStr(),
  currentOwner: importStr(),
  previousOwner: importStr(),
});

export const confirmAssetImportSchema = z.object({
  rows: z
    .array(
      z.object({
        rowIndex: z.number().int(),
        mapped: mappedAssetImportRowSchema,
        classification: z.enum(["new", "updated", "duplicate", "invalid"]),
        reason: z.string().max(500).optional(),
        existingId: z.string().optional(),
        existingAssetId: z.string().optional(),
        changedFields: z.array(z.string()).optional(),
      })
    )
    .max(2000),
});
