import { Router } from "express";
import { healthRouter } from "../modules/health/health.routes";
import { authRouter } from "../modules/auth/auth.routes";
import { usersRouter } from "../modules/users/users.routes";
import { auditRouter, loginHistoryRouter } from "../modules/audit/audit.routes";
import { departmentsRouter } from "../modules/departments/departments.routes";
import { locationsRouter } from "../modules/locations/locations.routes";
import { vendorsRouter } from "../modules/vendors/vendors.routes";
import { assetCategoriesRouter } from "../modules/assetCategories/assetCategories.routes";
import { licenseCategoriesRouter } from "../modules/licenseCategories/licenseCategories.routes";
import { settingsRouter } from "../modules/settings/settings.routes";
import { assetsRouter } from "../modules/assets/assets.routes";
import { licensesRouter } from "../modules/licenses/licenses.routes";
import { reportsRouter } from "../modules/reports/reports.routes";

export const apiRouter = Router();

apiRouter.use("/health", healthRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use("/audit-logs", auditRouter);
apiRouter.use("/login-history", loginHistoryRouter);
apiRouter.use("/departments", departmentsRouter);
apiRouter.use("/locations", locationsRouter);
apiRouter.use("/vendors", vendorsRouter);
apiRouter.use("/asset-categories", assetCategoriesRouter);
apiRouter.use("/license-categories", licenseCategoriesRouter);
apiRouter.use("/settings", settingsRouter);
apiRouter.use("/assets", assetsRouter);
apiRouter.use("/licenses", licensesRouter);
apiRouter.use("/reports", reportsRouter);
