import { Router } from "express";
import { healthRouter } from "../modules/health/health.routes";
import { authRouter } from "../modules/auth/auth.routes";
import { usersRouter } from "../modules/users/users.routes";
import { rolesRouter } from "../modules/roles/roles.routes";
import { permissionsRouter } from "../modules/permissions/permissions.routes";
import { auditRouter, loginHistoryRouter } from "../modules/audit/audit.routes";
import { notificationsRouter } from "../modules/notifications/notifications.routes";
import { departmentsRouter } from "../modules/departments/departments.routes";
import { locationsRouter } from "../modules/locations/locations.routes";
import { vendorsRouter } from "../modules/vendors/vendors.routes";
import { assetCategoriesRouter } from "../modules/assetCategories/assetCategories.routes";
import { licenseCategoriesRouter } from "../modules/licenseCategories/licenseCategories.routes";
import { settingsRouter } from "../modules/settings/settings.routes";
import { assetsRouter } from "../modules/assets/assets.routes";
import { assetAssignmentsRouter } from "../modules/assetAssignments/assetAssignments.routes";
import { assetTransfersRouter } from "../modules/assetTransfers/assetTransfers.routes";

export const apiRouter = Router();

apiRouter.use("/health", healthRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use("/roles", rolesRouter);
apiRouter.use("/permissions", permissionsRouter);
apiRouter.use("/audit-logs", auditRouter);
apiRouter.use("/login-history", loginHistoryRouter);
apiRouter.use("/notifications", notificationsRouter);
apiRouter.use("/departments", departmentsRouter);
apiRouter.use("/locations", locationsRouter);
apiRouter.use("/vendors", vendorsRouter);
apiRouter.use("/asset-categories", assetCategoriesRouter);
apiRouter.use("/license-categories", licenseCategoriesRouter);
apiRouter.use("/settings", settingsRouter);
apiRouter.use("/assets", assetsRouter);
apiRouter.use("/asset-assignments", assetAssignmentsRouter);
apiRouter.use("/asset-transfers", assetTransfersRouter);
