export const DEFAULT_ASSET_CATEGORIES: Array<{ name: string; prefix: string }> = [
  { name: "Laptop", prefix: "LAP" },
  { name: "Desktop", prefix: "DES" },
  { name: "Server", prefix: "SRV" },
  { name: "Monitor", prefix: "MON" },
  { name: "Printer", prefix: "PRN" },
  { name: "Scanner", prefix: "SCN" },
  { name: "Mobile", prefix: "MOB" },
  { name: "Tablet", prefix: "TAB" },
  { name: "Firewall", prefix: "FWL" },
  { name: "Router", prefix: "RTR" },
  { name: "Switch", prefix: "SWT" },
  { name: "Access Point", prefix: "AP" },
  { name: "NAS/Storage", prefix: "NAS" },
  { name: "UPS", prefix: "UPS" },
  { name: "Projector", prefix: "PRJ" },
  { name: "Keyboard", prefix: "KBD" },
  { name: "Mouse", prefix: "MSE" },
  { name: "Headset", prefix: "HST" },
  { name: "Other", prefix: "OTH" },
];

export const DEFAULT_LICENSE_CATEGORIES: string[] = [
  "Microsoft 365 Business Basic",
  "Microsoft 365 Business Standard",
  "Microsoft 365 Business Premium",
  "Microsoft 365 E3",
  "Microsoft 365 E5",
  "Microsoft Entra ID",
  "Intune",
  "Power BI",
  "Power Automate",
  "Copilot",
  "Adobe Acrobat",
  "Adobe Creative Cloud",
  "Antivirus",
  "EDR",
  "DLP",
  "SIEM",
  "Backup",
  "ERP",
  "CRM",
  "HRMS",
  "Accounting",
];
